// <auto-generated />
namespace DataRepositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GameServer_RemoveDatabaseName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameServer_RemoveDatabaseName));
        
        string IMigrationMetadata.Id
        {
            get { return "201805040935249_GameServer_RemoveDatabaseName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
