// <auto-generated />
namespace DataRepositories.Migrations.Dispatch
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserServerSlotRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserServerSlotRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300916241_UserServerSlotRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
